export interface Icontest {
    id:string,
    userId: string,
    userName:string,
    userImg:string,
    title: string,
    description: string,
    conditions: string,
    sectionId: string,
    deliveryDuration: string,
    contestDuration: string,
    winnersNum:string,
    firstWinner:string,
    skills:string,
    completed:boolean,
    accepted:boolean,
    Posts?:string,
    Views?:string,
    comment?:string,
    sectionName?:string,
    contestants?:string,
}